Add execution time to Windows shellout object
chef/mixlib-shellout pull request #239
Opened 2023-03-20 21:31 UTC by HeyItsGilbert

This adds a missing property (`execution_time`) to Windows.

## Description
Simple change to add an existing property.  Grabs the time when the shell out is complete and compares it to the start of the shell out. 

## Related Issue
#238 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-04-25 19:51 UTC, jaymzh requested changes

2023-04-25 19:51 UTC, jaymzh commented on lib/mixlib/shellout/windows.rb
> +                @execution_time = Time.now - start_wait
Probably want something similar around line 131 for the timeout case.

2023-08-15 19:33 UTC, johnmccrae commented
@HeyItsGilbert any updates for this? Its failing verify testing

2023-08-16 03:18 UTC, HeyItsGilbert commented
AFAICT it was failing testing because of a rubocop dependancy (requires 2.6 ruby or higher) which was unrelated to my change. Let me know if I was missing something.

2024-04-20 03:38 UTC, HeyItsGilbert commented
I totally forgot about this. If anyone is interested I think this is still ready to land.

2024-06-18 20:13 UTC, tpowell-progress commented
Superseded by #247

2024-06-18 20:13 UTC, closed without merging