[tests] Use rspec's ruby executable for run
chef/mixlib-shellout pull request #246
Opened 2024-06-12 16:36 UTC by dafyddcrosby

## Description

This fixes the assumption that `ruby` is always available from PATH.

## Related Issue

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [X] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-06-25 20:42 UTC, jaymzh approved these changes

2024-06-25 20:42 UTC, jaymzh requested changes
This seems to have broken windows...

2024-10-29 20:45 UTC, jaymzh commented
@dafyddcrosby - ping?

2025-02-11 21:31 UTC, dafyddcrosby commented
Closing since #255 did the trick for `select` latency

2025-02-11 21:31 UTC, closed without merging